/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entidades_graficas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Entidades.ConeccionAlLogin;
import java.util.regex.Pattern;


/**
 *
 * @author brall
 */
public class JFrame_Registro extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Registro
     */
    public JFrame_Registro() {
        initComponents();
    }
    
    //contraseña de 4 a 8 caracteres y debe contener números,
    //letras minúsculas y mayúsculas.
    private static final String COMPLEX_PASSWORD_REGEX =
            "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{4,8}$";
    
    private static final Pattern PASSWORD_PATTERN=
             Pattern.compile(COMPLEX_PASSWORD_REGEX);
    
    JFrame_Registro(JFrame_MenuInicio aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        BtnRegresar = new javax.swing.JButton();
        BtnCrearUsuario = new javax.swing.JButton();
        txtcontraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(66, 116, 144));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, 20));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 270, 20));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 270, 20));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 270, 20));

        BtnRegresar.setText("REGRESAR");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 110, 30));

        BtnCrearUsuario.setText("CREAR");
        BtnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 110, 30));
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 270, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        
        dispose();
        //Llamar al JFrame_MenuInicio
        JFrame_MenuInicio pantallaInicio= new JFrame_MenuInicio();
        //Centrar el JFrame
        pantallaInicio.setLocationRelativeTo(this);
        //hacer visible
        pantallaInicio.setVisible(true);
        //hacer visible a la ventana actual
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUsuarioActionPerformed
        
         // TODO add your handling code here:
        String Ddni=txtdni.getText();
        String Dnombre=txtNombre.getText();
        String Dtelefono=txtTelefono.getText();        
        String Dusuario=txtUsuario.getText();
        String Dcontraseña=txtcontraseña.getText();
        
        
        if(Ddni.isEmpty() || Dnombre.isEmpty() || Dtelefono.isEmpty() 
                || Dusuario.isEmpty() || Dcontraseña.isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Rellenar los espacios",
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!PASSWORD_PATTERN.matcher(Dcontraseña).matches()) {
            JOptionPane.showMessageDialog(this, " La contraseña debe cumplir "
                    + "con los siguientes requerimientos:\n"
                    + "- Entre 4 y 8 caracteres\n"
                    + "- Al menos una letra mayúscula\n"
                    + "- Al menos una letra minúscula\n"
                    + "- Al menos un número", 
                    
                    "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        usuarioRegistro(Ddni,Dnombre,Dtelefono,Dusuario,Dcontraseña); 
    }//GEN-LAST:event_BtnCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearUsuario;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtdni;
    // End of variables declaration//GEN-END:variables

    private void usuarioRegistro(String Ddni, String Dnombre, String Dtelefono, String Dusuario, String Dcontraseña) {
        
        
        Connection dbconn = ConeccionAlLogin.connectDB();
        if(dbconn != null){
        
        try {
            PreparedStatement st= (PreparedStatement)
                    dbconn.prepareStatement("INSERT INTO datos (dni,nombre,"
                            + "telefono,usuario,contraseña) VALUES(?,?,?,?,?)");
            
           
            st.setString(1,Ddni);
            st.setString(2,Dnombre);
            st.setString(3,Dtelefono);
            st.setString(4,Dusuario);
            st.setString(5,Dcontraseña);
            
            
            int res=st.executeUpdate();       
            JOptionPane.showMessageDialog(this, "Datos ingresados en la base "
                    + "de datos","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
            
            txtdni.setText("");
            txtNombre.setText("");
            txtTelefono.setText("");
            txtUsuario.setText("");           
            txtcontraseña.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(JFrame_MenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            System.out.println("la conexión no es valida ");
        }
    }
}
